tasks:
  - init: ./gradlew build
image: gitpod/workspace-mysql

vscode:
  extensions:
    - VisualStudioExptTeam.vscodeintellicode@1.2.2:VyaPhtK5JDcrioOPwlZlsw==
    - vscjava.vscode-spring-initializr@0.4.6:WOgtgIwX3Ngy4pM9ArXjCQ==
    - vscjava.vscode-java-test@0.22.0:BlvjRRJyZszeJzIS+xEHIA==
    - vscjava.vscode-java-debug@0.24.0:4bjzZag4ZW2bFcv6qiRCEg==
    - vscjava.vscode-java-dependency@0.6.0:XkyeyJWk/nK6xEO886ltYg==
    - vscjava.vscode-maven@0.20.1:gdyOPlzH3PU5IkrigIg85g==
    - Pivotal.vscode-concourse@1.14.0:UcwgfndJyAN/uFN4VxdUBA==
    - Pivotal.vscode-manifest-yaml@1.14.0:0/eEVpdpGiq1igMSzXX4KQ==
    - redhat.java@0.54.2:Q60n5quUtfd1EcwzkRq96A==
    - vscjava.vscode-spring-boot-dashboard@0.1.8:HcUY2EBWUzLI8LYU/I2Flg==
    - Pivotal.vscode-spring-boot@1.14.0:ZPqd7ysDHfq8h05jD/me8g==
    - GabrielBB.vscode-lombok@0.9.9:crmJ0s9mO0sdhxHl4cZaMw==
    - eamodio.gitlens@10.2.0:GNDO73Cmp0fYDiLNxVkbsQ==